---
- name: Deploy Site-B
  hosts: siteb
  become: yes

  tasks:
  - name: install docker prerequisities
    pip:
      name: docker

  - name: launch the apache-simple container on the site-b nodes
    docker_container:
      name: apache-simple
      image: quay.io/finneus85/ansible-for-devops-siteb
      ports:
        - "8080:8080"
